- hosts: localhost
  connection: local

  pre_tasks:
    - name: gather local facts
      setup:
      delegate_to: localhost
      delegate_facts: True

  tasks:
    - debug:
        var: ansible_facts
        verbosity: 3

    - name: check if ChromeOS
      set_fact:
        crostini=True
      when: ansible_facts.env.SOMMELIER_VERSION is defined

    - name: install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - aptitude
          - dnsutils
          - emacs
          - gawk
          - git-flow
          - htop
          - jq
          - netcat
          - psensor
          - python3-dev
          - python3-venv
          - python3-wheel
          - rdiff-backup
          - tree
          - whois
      become: yes
      ignore_errors: yes

    - name: copy suspend/resume helper systemd files
      copy:
        src: files/etc/systemd/system/{{ item }}
        dest: /etc/systemd/system
      become: yes
      with_items:
        - mariadb-resume.service
        - mariadb-suspend.service

    - name: enable MariaDB suspend/resume helper services
      systemd:
        enabled: yes
        name: "{{ item }}"
      become: yes
      with_items:
        - mariadb-resume.service
        - mariadb-suspend.service

    - name: copy config files
      copy:
        src: files/{{ item }}
        dest: $HOME
        force: no
      with_items:
        - .emacs
        - .gitconfig

    - name: set emacs as default editor
      lineinfile:
        path: $HOME/.bashrc
        line: "export EDITOR=emacs"
        regexp: "export +EDITOR=emacs"
        state: present
        backup: yes

    - name: add entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        regexp: "^{{ item }}"
        state: present
        backup: yes
      with_items:
        - "192.168.0.58	tippy"
        - "192.168.0.26	dumbo"
      become: yes

    - name: only on Chromebooks
      block:
        - name: copy systemd files to start ssh-agent
          copy:
            src: files/.config
            dest: $HOME
            force: no

        - name: set env variable for ssh-agent socket
          blockinfile:
            path: $HOME/.profile
            backup: yes
            block: |
              if [ -e $XDG_RUNTIME_DIR/ssh-agent.socket ]; then
                  export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
              fi
            marker_begin: "ssh-agent socket BEGIN"
            marker_end: "ssh-agent socket END"

        - name: copy Jetbrains startup scripts to $HOME/bin
          copy:
            src: files/bin/{{ item }}
            dest: $HOME/bin
          with_items:
            - pycharm
            - webstorm
            
      when: crostini is defined
