#!/bin/bash -e

sudo apt-get update
sudo apt-get install aptitude build-essential python-apt python3-apt python3-dev python3-venv

python3 -mvenv venv . --system-site-packages
source bin/activate

pip install ansible
ansible-playbook -K playbook.yml
