#!/bin/bash -e

sudo apt-get install build-essential python-apt python3-apt python3-dev python3-venv

python3 -mvenv venv --system-site-packages $(pwd)
source bin/activate
pip install ansible
ansible-playbook -v -K playbook.yml
